services:
  frontend:
    image: ghcr.io/alexanderoruban/pixel-to-pattern-frontend:latest
    container_name: frontend
    ports:
      - "80:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_BASE_URL=http://<YOUR_VM_IP>:3000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/alexanderoruban/pixel-to-pattern-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: